//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportesMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacoraProductos
    {
        public int id_bitacora_prod { get; set; }
        public int producto_id { get; set; }
        public System.DateTime fecha { get; set; }
        public string accion { get; set; }
    }
}
